# MODEL 1 .Data validation and pre-processing

In [1]:
#import package
import pandas as pd
import numpy as ny

In [2]:
#read dataset
data = pd.read_csv('water.csv')

In [3]:
# view head
data.head()

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0

In [4]:
#view tail
data.tail()

ph    Hardness        Solids  Chloramines     Sulfate  \
3271  4.668102  193.681735  47580.991603     7.166639  359.948574   
3272  7.808856  193.553212  17329.802160     8.061362         NaN   
3273  9.419510  175.762646  33155.578218     7.350233         NaN   
3274  5.126763  230.603758  11983.869376     6.303357         NaN   
3275  7.874671  195.102299  17404.177061     7.509306         NaN   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
3271    526.424171       13.894419        66.687695   4.435821           1  
3272    392.449580       19.903225              NaN   2.798243           1  
3273    432.044783       11.039070        69.845400   3.298875           1  
3274    402.883113       11.168946        77.488213   4.708658           1  
3275    327.459760       16.140368        78.698446   2.309149           1

In [5]:
# shape of the project
data.shape

(3276, 10)

In [6]:
# size ofthe data
data.size

32760

In [7]:
#columns
data.columns

Index(['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity',
       'Organic_carbon', 'Trihalomethanes', 'Turbidity', 'Potability'],
      dtype='object')

In [8]:
data.isnull()

ph  Hardness  Solids  Chloramines  Sulfate  Conductivity  \
0      True     False   False        False    False         False   
1     False     False   False        False     True         False   
2     False     False   False        False     True         False   
3     False     False   False        False    False         False   
4     False     False   False        False    False         False   
...     ...       ...     ...          ...      ...           ...   
3271  False     False   False        False    False         False   
3272  False     False   False        False     True         False   
3273  False     False   False        False     True         False   
3274  False     False   False        False     True         False   
3275  False     False   False        False     True         False   

      Organic_carbon  Trihalomethanes  Turbidity  Potability  
0              False            False      False       False  
1              False            False      False       False  
2              False            False      False       False  
3              False            False      False       False  
4              False            False      False       False  
...              ...              ...        ...         ...  
3271           False            False      False       False  
3272           False             True      False       False  
3273           False            False      False       False  
3274           False            False      False       False  
3275           False            False      False       False  

[3276 rows x 10 columns]

In [9]:
data.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [10]:
data.dropna()

ph    Hardness        Solids  Chloramines     Sulfate  \
3      8.316766  214.373394  22018.417441     8.059332  356.886136   
4      9.092223  181.101509  17978.986339     6.546600  310.135738   
5      5.584087  188.313324  28748.687739     7.544869  326.678363   
6     10.223862  248.071735  28749.716544     7.513408  393.663396   
7      8.635849  203.361523  13672.091764     4.563009  303.309771   
...         ...         ...           ...          ...         ...   
3267   8.989900  215.047358  15921.412018     6.297312  312.931022   
3268   6.702547  207.321086  17246.920347     7.708117  304.510230   
3269  11.491011   94.812545  37188.826022     9.263166  258.930600   
3270   6.069616  186.659040  26138.780191     7.747547  345.700257   
3271   4.668102  193.681735  47580.991603     7.166639  359.948574   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
3       363.266516       18.436524       100.341674   4.628771           0  
4       398.410813       11.558279        31.997993   4.075075           0  
5       280.467916        8.399735        54.917862   2.559708           0  
6       283.651634       13.789695        84.603556   2.672989           0  
7       474.607645       12.363817        62.798309   4.401425           0  
...            ...             ...              ...        ...         ...  
3267    390.410231        9.899115        55.069304   4.613843           1  
3268    329.266002       16.217303        28.878601   3.442983           1  
3269    439.893618       16.172755        41.558501   4.369264           1  
3270    415.886955       12.067620        60.419921   3.669712           1  
3271    526.424171       13.894419        66.687695   4.435821           1  

[2011 rows x 10 columns]

In [11]:
# information about dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 256.1 KB


In [12]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
3271    False
3272    False
3273    False
3274    False
3275    False
Length: 3276, dtype: bool

In [13]:
data.duplicated().sum()

0

In [14]:
# describe 
data.describe()

ph     Hardness        Solids  Chloramines      Sulfate  \
count  2785.000000  3276.000000   3276.000000  3276.000000  2495.000000   
mean      7.080795   196.369496  22014.092526     7.122277   333.775777   
std       1.594320    32.879761   8768.570828     1.583085    41.416840   
min       0.000000    47.432000    320.942611     0.352000   129.000000   
25%       6.093092   176.850538  15666.690297     6.127421   307.699498   
50%       7.036752   196.967627  20927.833607     7.130299   333.073546   
75%       8.062066   216.667456  27332.762127     8.114887   359.950170   
max      14.000000   323.124000  61227.196008    13.127000   481.030642   

       Conductivity  Organic_carbon  Trihalomethanes    Turbidity   Potability  
count   3276.000000     3276.000000      3114.000000  3276.000000  3276.000000  
mean     426.205111       14.284970        66.396293     3.966786     0.390110  
std       80.824064        3.308162        16.175008     0.780382     0.487849  
min      181.483754        2.200000         0.738000     1.450000     0.000000  
25%      365.734414       12.065801        55.844536     3.439711     0.000000  
50%      421.884968       14.218338        66.622485     3.955028     0.000000  
75%      481.792304       16.557652        77.337473     4.500320     1.000000  
max      753.342620       28.300000       124.000000     6.739000     1.000000

In [15]:
data['ph'].nunique()

2785

In [16]:
data['Hardness'].nunique()

3276

In [17]:
data["Solids"].nunique()

3276

In [18]:
# check the unique values
data["Chloramines"].nunique()

3276

In [19]:
data["Sulfate"].nunique()

2495

In [20]:
data["Conductivity"].nunique()

3276

In [21]:
data["Organic_carbon"].unique()

array([10.37978308, 15.18001312, 16.86863693, ..., 11.03906969,
       11.16894622, 16.14036763])

In [22]:
data["Trihalomethanes"].unique()

array([86.99097046, 56.32907628, 66.42009251, ..., 69.84540029,
       77.4882131 , 78.69844633])

In [23]:
data["Turbidity"].unique()

array([2.96313538, 4.50065627, 3.05593375, ..., 3.2988755 , 4.70865847,
       2.30914906])

In [24]:
data["Potability"].unique()

array([0, 1], dtype=int64)

In [25]:
data["Conductivity"].unique()

array([564.30865417, 592.88535913, 418.60621306, ..., 432.04478305,
       402.88311312, 327.45976046])

In [26]:
data["ph"].unique()

array([       nan, 3.71608008, 8.09912419, ..., 9.41951032, 5.12676292,
       7.87467136])

In [27]:
data.head()

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0

In [28]:
#min max values
print("minimum values of ph :", data["ph"].min())
print("mean values of ph :",data["ph"].mean())
print("maximum values of ph :", data["ph"].max())

minimum values of ph : 0.0
mean values of ph : 7.080794504276819
maximum values of ph : 13.999999999999998


In [29]:
#min max values
print("minimum values of ph :", data["Hardness"].min())
print("mean values of ph :",data["Hardness"].mean())
print("maximum values of ph :", data["Hardness"].max())

minimum values of ph : 47.432
mean values of ph : 196.36949601730177
maximum values of ph : 323.124


In [30]:
#min max values
print("minimum values of ph :", data["Solids"].min())
print("mean values of ph :",data["Solids"].mean())
print("maximum values of ph :", data["Solids"].max())

minimum values of ph : 320.942611274359
mean values of ph : 22014.09252607711
maximum values of ph : 61227.19600771213


In [31]:
#min max values
print("minimum values of ph :", data["Chloramines"].min())
print("mean values of ph :",data["Chloramines"].mean())
print("maximum values of ph :", data["Chloramines"].max())

minimum values of ph : 0.3520000000000003
mean values of ph : 7.122276793425787
maximum values of ph : 13.127000000000002


In [32]:
#min max values
print("minimum values of ph :", data["Sulfate"].min())
print("mean values of ph :",data["Sulfate"].mean())
print("maximum values of ph :", data["Sulfate"].max())

minimum values of ph : 129.00000000000003
mean values of ph : 333.7757766108134
maximum values of ph : 481.0306423059972


In [33]:
#min max values
print("minimum values of ph :", data["Conductivity"].min())
print("mean values of ph :",data["Conductivity"].mean())
print("maximum values of ph :", data["Conductivity"].max())

minimum values of ph : 181.483753985146
mean values of ph : 426.2051106825521
maximum values of ph : 753.3426195583046


In [34]:
#min max values
print("minimum values of ph:", data["Organic_carbon"].min())
print("mean values of ph :",data["Organic_carbon"].mean())
print("maximum values of ph:", data["Organic_carbon"].max())

minimum values of ph: 2.1999999999999886
mean values of ph : 14.284970247677336
maximum values of ph: 28.30000000000001


In [35]:
data.corr()

ph  Hardness    Solids  Chloramines   Sulfate  \
ph               1.000000  0.082096 -0.089288    -0.034350  0.018203   
Hardness         0.082096  1.000000 -0.046899    -0.030054 -0.106923   
Solids          -0.089288 -0.046899  1.000000    -0.070148 -0.171804   
Chloramines     -0.034350 -0.030054 -0.070148     1.000000  0.027244   
Sulfate          0.018203 -0.106923 -0.171804     0.027244  1.000000   
Conductivity     0.018614 -0.023915  0.013831    -0.020486 -0.016121   
Organic_carbon   0.043503  0.003610  0.010242    -0.012653  0.030831   
Trihalomethanes  0.003354 -0.013013 -0.009143     0.017084 -0.030274   
Turbidity       -0.039057 -0.014449  0.019546     0.002363 -0.011187   
Potability      -0.003556 -0.013837  0.033743     0.023779 -0.023577   

                 Conductivity  Organic_carbon  Trihalomethanes  Turbidity  \
ph                   0.018614        0.043503         0.003354  -0.039057   
Hardness            -0.023915        0.003610        -0.013013  -0.014449   
Solids               0.013831        0.010242        -0.009143   0.019546   
Chloramines         -0.020486       -0.012653         0.017084   0.002363   
Sulfate             -0.016121        0.030831        -0.030274  -0.011187   
Conductivity         1.000000        0.020966         0.001285   0.005798   
Organic_carbon       0.020966        1.000000        -0.013274  -0.027308   
Trihalomethanes      0.001285       -0.013274         1.000000  -0.022145   
Turbidity            0.005798       -0.027308        -0.022145   1.000000   
Potability          -0.008128       -0.030001         0.007130   0.001581   

                 Potability  
ph                -0.003556  
Hardness          -0.013837  
Solids             0.033743  
Chloramines        0.023779  
Sulfate           -0.023577  
Conductivity      -0.008128  
Organic_carbon    -0.030001  
Trihalomethanes    0.007130  
Turbidity          0.001581  
Potability         1.000000

In [36]:
data.corr().describe()

ph   Hardness     Solids  Chloramines    Sulfate  Conductivity  \
count  10.000000  10.000000  10.000000    10.000000  10.000000     10.000000   
mean    0.099952   0.083662   0.069008     0.090278   0.071639      0.099184   
std     0.319741   0.325310   0.333148     0.321055   0.332250      0.316922   
min    -0.089288  -0.106923  -0.171804    -0.070148  -0.171804     -0.023915   
25%    -0.026652  -0.028519  -0.064336    -0.027662  -0.028600     -0.014123   
50%     0.010779  -0.014143   0.000550    -0.005145  -0.013654      0.003542   
75%     0.037281  -0.000546   0.018117     0.022105   0.024984      0.017418   
max     1.000000   1.000000   1.000000     1.000000   1.000000      1.000000   

       Organic_carbon  Trihalomethanes  Turbidity  Potability  
count       10.000000        10.000000  10.000000   10.000000  
mean         0.102592         0.094100   0.091514    0.098713  
std          0.316251         0.318616   0.319682    0.317287  
min         -0.030001        -0.030274  -0.039057   -0.030001  
25%         -0.013119        -0.013209  -0.020221   -0.012409  
50%          0.006926        -0.003929  -0.004803   -0.000988  
75%          0.028365         0.006186   0.004939    0.019617  
max          1.000000         1.000000   1.000000    1.000000

In [37]:
data["Trihalomethanes"].value_counts()

86.990970    1
84.798956    1
54.473935    1
77.730814    1
90.394895    1
            ..
73.723070    1
46.682597    1
70.168389    1
81.592362    1
78.698446    1
Name: Trihalomethanes, Length: 3114, dtype: int64

In [38]:
pd.Categorical(data["Turbidity"]).describe()

counts     freqs
categories                          
1.45                     1  0.000305
1.4922066153042484       1  0.000305
1.4961009425719864       1  0.000305
1.6415150097935705       1  0.000305
1.6597993845044374       1  0.000305
...                    ...       ...
6.357438520067428        1  0.000305
6.389161009216368        1  0.000305
6.494249467472996        1  0.000305
6.494748555990993        1  0.000305
6.739                    1  0.000305

[3276 rows x 2 columns]

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 256.1 KB


In [40]:
data.columns

Index(['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity',
       'Organic_carbon', 'Trihalomethanes', 'Turbidity', 'Potability'],
      dtype='object')

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
le = LabelEncoder()
var_mod = (['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity',
       'Organic_carbon', 'Trihalomethanes', 'Turbidity', 'Potability'])
for i in var_mod:
           data[i] = le.fit_transform(data[i]). astype(int)

In [43]:
data.head()

ph  Hardness  Solids  Chloramines  Sulfate  Conductivity  Organic_carbon  \
0  2785      1997    1619         1791     2009          3104             369   
1    49        86    1283         1228     2495          3195            2001   
2  2107      2676    1466         2997     2495          1589            2549   
3  2233      2373    1794         2410     1819           782            2931   
4  2509       974    1175         1151      663          1278             663   

   Trihalomethanes  Turbidity  Potability  
0             2825        341           0  
1              801       2457           0  
2             1544        406           0  
3             3058       2627           0  
4               59       1813           0